### ISSUE TITLE
python3.4

### ISSUE THREAD

**Issue by cmabastar** [niclabs/flask-rest-boilerplate#1]
Hello, 

I'm using python3.4 is this supported? When i run i get:

(env)➜  flask-rest-boilerplate git:(master)   python3.4 manage.py
Traceback (most recent call last):
  File "manage.py", line 3, in <module>
    from app import app, db
  File "/usr/home/cmabastar/flask-rest-boilerplate/app/__init__.py", line 18, in <module>
    from auth import AuthProvider
ImportError: No module named 'auth'

**Comment by pipex** [comment]
Yes, I've only tested the boilerplate with Python 2.7 unfortunately. I made a quick pass with [modernize](http://python-modernize.readthedocs.org/en/latest/) and it should be simple to perform a migration (there are mostly import issues)

I hope to find some time in the following weeks to develop and test the migration.

**Comment by pipex** [comment]
It should be working now
